#!/bin/dash

if [ "$#" -ne 0 ]
then
    echo "usage: $0" 1>&2
    exit 1
fi

if [ -d ".got" ]
then
    echo "$0: error: .got already exists"
    exit 1
else
    mkdir -p ".got" ".got/index" ".got/branches/master" ".got/commits"
    touch ".got/log"  
    echo "master" > ".got/HEAD"
    echo "Initialized empty got repository in .got"
fi
